FROM snakepacker/python:all
RUN apt-install \
	libfreetype6-dev \
	libfribidi-dev \
	libgif-dev \
	libharfbuzz-dev \
	libimagequant-dev \
	libjpeg-dev \
	libjpeg8-dev \
	liblcms2-dev \
	libopenjp2-7-dev \
	libpng-dev \
	libtiff-dev \
	libtiff5-dev \
	libwebp-dev \
	libxcb1-dev \
	zlib1g-dev
